root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main 2024/17/main.go"
  # cmd = "go build -o ./tmp/main 2022/11/main.go"
  # cmd = "go test ./src/2020/01 -bench=."
  delay = 100
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = ["_test.go", ".null-ls"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = ["data", "internal", "2020", "2021", "2022", "2023", "2024"]
  include_ext = ["go", "txt"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
